version: "3"
services:
  webserver:
    container_name: shop
    image: dockerfile
    restart: always
    build: .
    ports:
      - "5000:3000"
    links:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
